import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Uber Clone",
  description: "Generated by Niva",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider afterSignInUrl="/callback" afterSignUpUrl="/callback">
      <html lang="en">
        <head>
    
  </head>
        <body className="bg-gray-100 text-gray-900 min-h-screen">
          
          {/* ✅ Correct Razorpay script loading */}
          

          <div className="flex">
            <aside className="hidden md:block"></aside>

            <main className="flex-1 ml-56 p-6">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
